### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by alexgrach** [jbbarth/redmine_omniauth_cas#23]
Hello.
Unable to install plugin. Fails with error:

rake redmine:plugins RAILS_ENV=production --trace
** Invoke redmine:plugins (first_time)
** Execute redmine:plugins
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant ActiveSupport::Reloader
/usr/share/redmine/plugins/redmine_omniauth_cas/init.rb:8:in `<top (required)>'
/usr/share/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:146:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:652:in `block in load_config_initializer'
/usr/lib/ruby/vendor_ruby/active_support/notifications.rb:166:in `instrument'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:651:in `load_config_initializer'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:615:in `each'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:615:in `block in <class:Engine>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:328:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/usr/share/redmine/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

**Comment by esbaixauli** [comment]
Same error here on Redmine 3.4.11.stable, any luck installing?

**Comment by nanego** [comment]
With Redmine 3, you should use an older version, not the master branch of the plugin.
You can use this tag: https://github.com/jbbarth/redmine_omniauth_cas/tree/v3.4.6
